<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>Open Source Alternative Solutions - Web</title>
<meta name="keywords" content="open source alternative, web servers, open web servers, iis alternative, apache alternatives, programming languages, web editors, reporting, web analysis, open source online support" />
<meta name="description" content="opensitesolutions.com recommending open source web development solutions as an alternative to commercial software" />
<meta name="author" content="Webmaster">
<META HTTP-EQUIV="CACHE-CONTROL" CONTENT="NO-CACHE">
<link href="/style.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="outer">
