<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
   "http://www.w3.org/TR/html4/strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>Open Source Alternative Software - Medical</title>
<meta name="keywords" content="open source alternative, alternative to Medical Manager, alternative to Health Pro, alternative to Misys" />
<meta name="description" content="opensitesolutions.com recommending open source alternative to medical manager, health pro, Misys" />
<meta name="author" content="Webmaster">
<META HTTP-EQUIV="CACHE-CONTROL" CONTENT="NO-CACHE">
<link href="/style.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="outer">
