<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>Open Source Alternative Solutions for the network</title>
<meta name="keywords" content="open source as alternative, exchange alternative, groupware, network access control, backup software, software testing, cloning, imaging, open management, open network" />
<meta name="description" content="opensitesolutions.com providing open source solutions as an alternative to commercial software" />
<META HTTP-EQUIV="CACHE-CONTROL" CONTENT="NO-CACHE">
<link href="/style.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="outer">
