<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>Open Source Alternative Software</title>
<meta name="keywords" content=" open source software for business, content management, open network, crm, windows alternative, open source erp, open source business intellignece, web coloboration, web conferencing, imaging, cloning, backup" />
<meta name="description" content="opensitesolutions.com alternative software soltuions" />
<meta name="author" content="Webmaster">
<meta http-equiv="pragma" content="no-cache">
<META HTTP-EQUIV="CACHE-CONTROL" CONTENT="NO-CACHE">
<link href="/style.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="outer">
