<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>Open Source Alternative Solutions Articles</title>
<meta name="keywords" content="open source as articles, apache security, open defense, modsecurity, application firewall" />
<meta name="description" content="opensitesolutions.com articles providing solutions using open source software" />
<meta name="author" content="Webmaster">
<meta http-equiv="pragma" content="no-cache">
<META HTTP-EQUIV="CACHE-CONTROL" CONTENT="NO-CACHE">
<link href="/style.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="outer">
