<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>Open Source for Education</title>
<meta name="keywords" content="open source alternative, content managment, math, drupal, moodle,library, LIVECD, open source education on cd" />
<meta name="description" content="opensitesolutions.com recommending open source software and solutions for education as an alternative to commercial software" />
<meta name="author" content="Webmaster">
<META HTTP-EQUIV="CACHE-CONTROL" CONTENT="NO-CACHE">
<link href="/style.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="outer">
