<script type='text/javascript'><!--
ch_target = 'http://cmills.shoplinc.com';
ch_client = 'cmills';
ch_width = 160;
ch_height = 160;
ch_type = 'mpu';
ch_non_contextual = 1;
ch_default_category = '0';
var ch_queries = new Array();
var ch_selected=Math.floor((Math.random()*ch_queries.length));
if ( ch_selected < ch_queries.length ) {
ch_query = ch_queries[ch_selected];
}
//--></script>
<script  src='http://scripts.chitika.net/eminimalls/mm.js' type='text/javascript'>
</script>
