<script type="text/javascript"><!--
ch_client = "cmills";
ch_type = "cpu";
ch_width = 120;
ch_height = 250;
ch_non_contextual = 1;
ch_att = "Hot Products";
ch_shoplinc_url = "http://cmills.shoplinc.com";
ch_font_max = "30";
ch_font_min = "8";
ch_font_change = "2";
ch_tags_max = "20";
var ch_queries = new Array( );
var ch_selected=Math.floor((Math.random()*ch_queries.length));
if ( ch_selected < ch_queries.length ) {
ch_query = ch_queries[ch_selected];
}
//--></script>
<script  src="http://scripts.chitika.net/eminimalls/shopcloud.js" type="text/javascript">
</script>
