<!--- begin footer --->

<!-- begin footer content --->
<div class="footer">
  <hr>
  <p>Copyright &copy; 2006-2016 <a href="http://www.opensitesolutions.com" target="new_window">www.opensitesolutions.com</a></p>
</div>
<!-- end footer content --->

<!-- google analytics tracking code --->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-744038-1', 'auto');
  ga('send', 'pageview');
</script>
<!-- end google analytics tracking code --->

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</body>
</html>
<!--- end footer --->
