<center>
<!-- Start Bluehost advertising -->
<a href="//www.bluehost.com/track/cmills/bottom-link" target="_blank">
<img border="0" src="//bluehost-cdn.com/media/partner/images/cmills/760x80/bh-ppc-banners-dynamic-760x80.png">
</a>
<!-- End Start Bluehost advertising -->

</center>
 <!-- Footer -->

        <div id="footer">

	<center>


        </center>

                <p>Copyright &copy; 2006-2008 <a href="http://www.opensitesolutions.com" target="new_windo">www.opensitesolutions.com</a>. Designed by <a href="http://www.freecsstemplates.org">Free CSS Templates</a></p>
		<img src="/images/get_apache_80x15_1.png"><img src="/images/powered_php_80x15.png">
        </div>
        <!-- EndFooter -->

	</div>

<!-- Non presentation code -->

<!-- Piwik Tracking Code -->
<script type="text/javascript">
  var _paq = _paq || [];
  _paq.push(["setDomains", ["*.www.opensitesolutions.com"]]);
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="//analytics.opensitesolutions.com/piwik/";
    _paq.push(['setTrackerUrl', u+'piwik.php']);
    _paq.push(['setSiteId', 1]);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
  })();
</script>
<noscript><p><img src="//analytics.opensitesolutions.com/piwik/piwik.php?idsite=1" style="border:0;" alt="" /></p></noscript>
<!-- End Piwik Code -->



<!-- Start Google Analytics -->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-744038-1', 'auto');
  ga('send', 'pageview');

</script>
<!-- End Google Analytics -->

</body>
</html>
