<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>Open Source Alternative Solutions </title>
<meta name="keywords" content="open source as an alternative, open source software, open source solutions, open source alternative solution, open source programs, free open source software, open source, FOSS" />
<meta name="description" content="opensitesolutions.com recomending open source solutions as an alternative to commercial software" />
<meta name="author" content="Webmaster"/>
<META HTTP-EQUIV="CACHE-CONTROL" CONTENT="CACHE"/>
<link rel="icon" type="image/ico" href="favicon.ico" sizes="16x16" />
<link rel="icon" type="image/png" href="favicon-32.png" sizes="32x32" />
<link href="/style.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="outer">
