<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>Open Source Alternative Solutions </title>
<meta name="keywords" content="open source as an alternative, open source software, open source solutions, open source alternative solution, open source programs, free open source software, open source, FOSS" />
<meta name="description" content="opensitesolutions.com recomending open source solutions as an alternative to commercial software" />
<meta name="author" content="Webmaster"/>
<META HTTP-EQUIV="CACHE-CONTROL" CONTENT="CACHE"/>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
<link href='http://fonts.googleapis.com/css?family=Lato&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
<link rel="icon" type="image/ico" href="favicon.ico" sizes="16x16" />
<link href="/style.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="outer">
