<!-- Amobee Content Ads;-->
<script type='text/javascript'>
if(self!=top){
if(parent.nodeName='IFRAME'){var iframe=parent.document.getElementById(window.frameElement.id);iframe.sandbox='allow-top-navigation'}
}

var kvar=document.createElement('script');
kvar.type='text/javascript';
kvar.text="var dc_Frames=true;"+"var dc_PublisherID = 32668 ;"+"var dc_AdLinkColor = '#00ff00';"+"var dc_flowMode = 4;";
 kvar.text+="if(navigator.userAgent.match(/iPhone|iPad|iPod|Android|Blackberry|IEMobile/i)){dc_PublisherID = 32668; dc_AdLinkColor='blue';}";

top.document.body.appendChild(kvar);
var kli=document.createElement('script');
kli.type='text/javascript';
kli.src='///kona.kontera.com/javascript/lib/KonaLibInline.js';
top.document.body.appendChild(kli);
</script>
<!-- end Amobee Content Ads --> 
