<!--- begin lef column --->

<div class="col-md-2">

  <div class="panel panel-default">
    <div class="panel-heading">
      Consulting services
    </div>
    <div class="panel-body">
        Implementing, installing and supporting open source applications in your environment email
        <a href="mailto:consulting@opensitesolutions.com">consulting</a>
    </div>
  </div>

<div>
    <!--- Responsive adds --->
            <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <!-- opensitesolutions.com -->
    <ins class="adsbygoogle"
         style="display:block"
         data-ad-client="ca-pub-9703614120192799"
         data-ad-slot="1063171417"
         data-ad-format="auto"></ins>
    <script>
    (adsbygoogle = window.adsbygoogle || []).push({});
    </script>
            </script>
    <!--- end responsive adds --->
</div>
</div>

<!--- end left column --->
