<!--- begin lef column --->

<div class="col-md-2">

  <div class="panel panel-default">
    <div class="panel-heading">
      Consulting services
    </div>
    <div class="panel-body">
        Implementing, installing and supporting open source applications in your environment email
        <a href="mailto:consulting@opensitesolutions.com">consulting</a>
    </div>
  </div>

<div>
    <!--- Responsive adds --->
      <!-- Google tag (gtag.js) -->
      <script async src="https://www.googletagmanager.com/gtag/js?id=G-TBZ9TTNLYH"></script>
      <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'G-TBZ9TTNLYH');
      </script>
    <!--- end responsive adds --->
</div>
</div>

<!--- end left column --->
