<!--- begin navbar --->

<!--- begin Navigation header --->
<nav class="navbar navbar-inverse navbar-fixed-top">

  <div class="container-fluid">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/index.php">Open Site Solutions</a>
    </div>

    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">Articles<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="/services/docs/apache.php">Apache</a></li>
            <li><a href="/services/docs/favicon.php">Favicon</a></li>
            <li><a href="/services/docs/firewall.php">Firewall</a></li>
            <li><a href="/services/docs/freebsdldap_guide.php">LDAP</a></li>
          </ul>
        </li>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">Business<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="/services/business.php">Applications</a></li>
            <li><a href="/index.php">Desktop</a></li>
            <li><a href="/services/communication.php">Communication</a></li>
            <li><a href="/services/altcisco.php">Routing Software</a></li>
            <li><a href="/services/altcallmanager.php">Phone System</a></li>
          </ul>
        </li>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">Private Sector<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="/services/education.php">Education</a></li>
            <li><a href="/services/openmedical.php">Medical</a></li>
          </ul>
        </li>
        <li><a href="/services/integrators.php">Integrators</a></li>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">Network<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="/services/network-mgmt.php">Network Management</a></li>
            <li><a href="/services/network.php">Network</a></li>
            <li><a href="/services/altghost.php">Imaging</a></li>
          </ul>
        </li>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">Systems<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="/services/idm.php">Identity Management</a></li>
            <li><a href="/services/databases.php">Database</a></li>
            <li><a href="/services/altghost.php">Disk Cloning</a></li>
            <li><a href="/services/dnstools.php">DNS Tools</a></li>
            <li><a href="/services/monitoring.php">Monitoring</a></li>
            <li><a href="/services/mail.php">Mail</a></li>
            <li><a href="/services/privacy.php">Privacy</a></li>
            <li><a href="/services/system.php">Systems</a></li>
            <li><a href="/services/virtualization.php">Virtualization</a></li>
            <li><a href="/services/voice.php">Voice</a></li>
            <li><a href="/services/web.php">Web Development</a></li>
          </ul>
        </li>
      </ul>
    </div>


  </div>
</nav>
<!--- end Navigation header --->
<!--- end navbar --->
