<!--- begin right column --->
<div class="col-md-2">

    <!-- begin content -->
    <div class="list-group">
        <a href="#" class="list-group-item active">
        <h4 class="list-group-item-heading">Open Site Solutions</h4>
          <p>
          Open Site Solutions informing about integrators, hardware and Open Source applications that can be used as an alternative to commercial software.
          Open source solutions are comprised of different software applications bundled together to create a unique and most times better solution than commercial software.
          <br>
          Open source is not <b><a href="http://en.wikipedia.org/wiki/Freeware">freeware</a></b> or <b><a href="http://en.wikipedia.org/wiki/Shareware">shareware</a></b>.
          Open Source software is built from a community of developers committed to a common goal who then make the source code and program available to download allowing modifications and contributions back into the source code.
          </p>
        </a>
    </div>

    <div>
        <!--- Responsive adds --->
                <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
        <!-- opensitesolutions.com -->
        <ins class="adsbygoogle"
             style="display:block"
             data-ad-client="ca-pub-9703614120192799"
             data-ad-slot="1063171417"
             data-ad-format="auto"></ins>
        <script>
        (adsbygoogle = window.adsbygoogle || []).push({});
        </script>
                </script>
        <!--- end responsive adds --->
    </div>

    <!--- end content --->
</div>
<!--- end right column --->
