<div class="col-md-2">
<!--- begin right column --->
    <!-- begin content -->
    <!-- begin explaination about open site solutions --->
    <div class="panel panel-default">
      <div class="panel-heading">
        Open Site Solutions
      </div>
      <div class="panel-body">
        <p>
          Informing about integrators, hardware and Open Source applications that can be used as alternatives to commercial properiertary software.
          Open source solutions are comprised of different software applications bundled together to create a unique and most times better solution than commercial software.
        </p>
      </div>
    </div>
    <!--- end explaination about open site solutions --->
          <hr>

    <!--- Begin Responsive adds --->
    <div>
            <!-- Google tag (gtag.js) -->
            <script async src="https://www.googletagmanager.com/gtag/js?id=G-TBZ9TTNLYH"></script>
            <script>
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());

              gtag('config', 'G-TBZ9TTNLYH');
            </script>
    </div>
    <!--- end responsive adds --->
    
        <hr>

    <!--- begin explaination about open source software --->
    <div class="panel panel-default">
        <div class="panel-heading">
            Open Source software
        </div>
        <div class="panel-body">
          <div class="panel-body">
            <p>
              Open source is not <b><a href="http://en.wikipedia.org/wiki/Freeware">freeware</a></b> or <b><a href="http://en.wikipedia.org/wiki/Shareware">shareware</a></b>.
              Open Source software is built from a community of developers committed to a common goal who then make the source code and program available to download allowing modifications and contributions back into the source code.
            </p>
          </div>
        </div>
    </div>
    <!--- end explaination about open source software --->
    <!--- end content --->

<!--- end right column --->
</div>
