<div id="header">
                <a href="#"><img src="/images/logo.png"></a>
        </div>
        <div id="menu">
                <ul>
                        <li class="first"><a href="/home.php" accesskey="1" title="">Home</a></li>
                        <li><a href="/services/index.php" accesskey="2" title="">Applications</a></li>
                        <li><a href="/services/integrators.php" accesskey="3" title="">Integrators</a></li>
                        <li><a href="/services/docs/" accesskey="4" title="">Articles</a></li>
                        <li><a href="/aboutus.php" accesskey="5" title="">About Us</a></li>
                        <li><a href="/contactus.php" accesskey="6" title="">Contact Us</a></li>
                </ul>
        </div>
